analyses:
  - name: '01 Colors'
    text: 'Telefonabonnemang och deras färgval'
    link: '01_colors'

  - name: '02 Load'
    text: 'Laddningstider hos högskole- och universitetshemsidor'
    link: '02_load'

  - name: '03 Design Principles'
    text: 'Designprinciper på musikers personsidor'
    link: '03_design_principles'
