analyses:
  - name: '01 Colors'
    text: 'Telefonabonnemang och deras färgval'
    link: '01_colors'

  - name: '02 Load'
    text: 'Inte gjort än'
    link: '02_load'

  - name: '03 Design Principles'
    text: 'Inte gjort än'
    link: '03_design_principles'
