reports:
  - name: 'Kmom01'
    text: 'Sådär, då var vi klara med första delen!'
    link: 'kmom01'
    
  - name: 'Kmom02'
    text: 'Gött, då var vi ingång med SCSS :)'
    link: 'kmom02'

  - name: 'Kmom03'
    text: 'Jadå, nu kör vi! CSS-Grid och Flexbox!'
    link: 'kmom03'

  - name: 'Kmom04'
    text: 'Att få göra en gruppavgift var roligt.'
    link: 'kmom04'

  - name: 'Kmom05'
    text: 'Det var intressant att se att så många webbplatser led av…'
    link: 'kmom05'

  - name: 'Kmom06'
    text: 'Det är intressant att lära sig om lite riktiga designkoncept.'
    link: 'kmom06'
    
  - name: 'Kmom10'
    text: 'Inte gjort än'
    link: 'kmom10'
    wide: true
